name: pongKeeper CD
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup git token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.SECRET }}

      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy gh-pages
        env:
          DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          GITHUB_TOKEN: ${{secrets.SECRET}} 
        run:
          yarn deploy
